name: 'marketing_analytics'
version: '1.0.0'
config-version: 2

profile: 'marketing_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  marketing_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  marketing_analytics:
    +schema: raw
